name: Example Workflow with Warning and File Upload

on:
  pull_request:
    types: [opened, reopened, ready_for_review, converted_to_draft]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install jq
        run: sudo apt-get install jq

      - name: Read failures_summary.json and add annotations
        run: |
          python scripts/tmp/test.py
          
          # echo "cat failures_summary.json"
          # cat failures_summary.json
          # echo

          # JSON_CONTENT=$(cat failures_summary.json)
          # ESCAPED_JSON_CONTENT=$(echo "$JSON_CONTENT" | jq -c '.')

          # for failure in ESCAPED_JSON_CONTENT; do
          #   echo "::warning::Failures detected: $failure
          # done
          
